### ISSUE TITLE
Where is cone ? :)

### ISSUE THREAD

**Issue by Suprhimp** [dipeshdulal/geodesic-heat-method#1]
I can't see `cone-with-logo.fbx`file.. so I can't check it..

Can you add that model please? 

Thanks!

**Comment by makc** [comment]
the cone is gone, man. the cone is gone.

**Comment by dipeshdulal** [comment]
@Suprhimp @makc The cone is gone 😁

I added `doghead.obj` model and the code should work now. Can you check? 🙏

<img width="635" alt="image" src="https://github.com/dipeshdulal/geodesic-heat-method/assets/8201857/1a2396f0-8e77-4cd7-b682-e6b83924d4f0">

**Comment by Suprhimp** [comment]
it's works very well! Thanks!
